### ISSUE TITLE
ZDEMO_EXCEL_CHECKER not checking 37, 41, 42, 45 to 48

### ISSUE THREAD

**Issue by sandraros** [abap2xlsx/demos#5]
When running `ZDEMO_EXCEL_CHECKER`, in the list of demo programs, the following programs don't appear although the program tries internally to check them:
- `ZDEMO_EXCEL37`
- `ZDEMO_EXCEL41` 
- `ZDEMO_EXCEL42`
- `ZDEMO_EXCEL45`
- `ZDEMO_EXCEL46`
- `ZDEMO_EXCEL47`
- `ZDEMO_EXCEL48`

**Comment by AndreaBorgia-Abo** [comment]
WIP, just some quick notes: 
* in A4H, 37 throws an exception because there is no matching entry in SMW0
* tyring to add one gives a missing mime type error.

Todo:
* check if other missing entries also throw an exception
* check in NPL if mime types are missing there too
* add them and retry
* normalize filenames for demos, as last step.
